#pragma once

#include <limits>
#include <cstdint>

// For NeoGraph
#define VERTEX_GROUP_BITS 6
constexpr uint64_t VERTEX_GROUP_SIZE = 1 << VERTEX_GROUP_BITS;
constexpr uint64_t VERTEX_GROUP_MASK = (1 << VERTEX_GROUP_BITS) - 1;
constexpr uint64_t INDEPENDENT_MAP_BLOCK_NUM = (VERTEX_GROUP_SIZE + 63) / 64;
#define RANGE_LEAF_SIZE 512 // 512 by default
#define ART_EXTRACT_THRESHOLD 8192  // 8192 by default
#define ART_LEAF_SIZE 256 // 16 * 16
#define SEQUENTIAL_SCAN_THRESHOLD 16
#define EDGE_INSERT_VEC_THRESHOLD 0.8
#define BATCH_UPDATE_THRESHOLD (1 << 2)
#define INIT_READER_NUM 32
#define INIT_WRITER_NUM 64
// For Property
#define VERTEX_PROPERTY_NUM 0
#define EDGE_PROPERTY_NUM 1

#define COMPRESSION_ENABLE 1
#define FROM_CLUSTERED_TO_SMALL_VEC_ENABLE 0
#define SIMULATE_PER_EDGE_VERSIONING_ENABLE 0
// For segment pool
#define SEGMENT_POOL_INIT_SIZE 256
#define BATCH_UPDATE_THREAD_NUM 31
#define BATCH_UPDATE_ENABLE_THRESHOLD 32

#define VERSION_HEAD_MASK 0x8000000000000000